### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Praisepaul** [benduBytes/DSA#1]
Please update your README.md file as it will be very much beneficial for people watching your repository or want to refer someday. It will also be beneficial for yourself too. :)

**Comment by benduBytes** [comment]
I had just stated it, but even now, I'm not sure how to handle the directories inside the repository so that the README is appropriate and clear.I appreciate your support and will update the .md file.

**Comment by Praisepaul** [comment]
Good luch and Happy Coding!!!
